source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'require_all'
gem 'rack'
gem 'rake'
gem 'json'
gem 'activerecord'
gem 'mysql2', '~> 0.3.18'
gem 'dotenv'
gem 'aws-sdk', '~> 2'
gem 'nokogiri'
gem 'byebug'
gem 'migration_data'
gem 'xml-sitemap'
gem 'httparty'

group :development, :test do
	gem 'rerun'
	gem 'rspec-sinatra'
	gem 'rspec'
	gem 'webmock'
	gem 'capybara'
end
